version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/todo_db
      JWT_SECRET: sua_chave_secreta

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
